source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXiOSUtils_Example', :exclusive => true do
  pod "BXiOSUtils", :path => "../"
end

target 'BXiOSUtils_Tests', :exclusive => true do
  pod "BXiOSUtils", :path => "../"

  
end
